### ISSUE TITLE
BepInEx issue

### ISSUE THREAD

**Issue by fewioewfoiuj** [artv15/BBCR-Return-Null-BepInEx-Mod#1]
Hello.
I installed BepInEx, and there is no exe file, and I am running on Windows 10 x64. Is there a solution?

**Comment by artv15** [comment]
Can you send a screenshot of the game folder?

**Comment by Benefond** [comment]
Very sure that you put BepInEx in the Baldi's Basics Classic Remastered folder

**Comment by artv15** [comment]
> > Can you send a screenshot of the game folder?
> 
> Of course, let me see. Also, Do I need to send the screenshot of the BepInEx folder too? ![baldis basics classic remastered](https://user-images.githubusercontent.com/119624641/205336112-dfa1346c-9051-458a-86ef-2cc8e94898c7.PNG)

You need to move the contents of BepInEx archive inside the game's folder

**Comment by fewioewfoiuj** [comment]
> > > Can you send a screenshot of the game folder?
> > 
> > 
> > Of course, let me see. Also, Do I need to send the screenshot of the BepInEx folder too? ![baldis basics classic remastered](https://user-images.githubusercontent.com/119624641/205336112-dfa1346c-9051-458a-86ef-2cc8e94898c7.PNG)
> 
> You need to move the contents of BepInEx archive inside the game's folder

The data?

**Comment by fewioewfoiuj** [comment]
Also, I launched the game once and it didn't generate the folders.

**Comment by artv15** [comment]
You need to move everything inside the root folder (where Baldi.exe is located)

**Comment by fewioewfoiuj** [comment]
Including the folder Plugins in BALDI_data?

**Comment by artv15** [comment]
No, you should not move anything to Data folder. You need to move everything inside root (where exe is located)
________________________________

**Comment by fewioewfoiuj** [comment]
Tell me the instructions one by one. I can be confused.

**Comment by fewioewfoiuj** [comment]
Alright I did it, Thanks!
