### ISSUE TITLE
Notebook issue

### ISSUE THREAD

**Issue by GoldenTheDev** [artv15/BBCR-Return-Null-BepInEx-Mod#3]
With notebooks it always goes down to 0 and it doesnt add after you collect one

**Comment by artv15** [comment]
Can you specify when exactly does this happen?

**Comment by artv15** [comment]
Closing this one due to inactivity, if problem still persists, reopen the issue.

**Comment by GoldenTheDev** [comment]
I only realized it does this if you haven't seen null in all of the endings yet still unlocked null mode
